{% set python_min = "3.10" %}
{% set name = "PyActiveStorage" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 8931b55898be7b8e317bc3264d3396005330aa1e5a24110dfb675daa83a3ea93

build:
  number: 0
  # not 100% noarch; middleware is not-Win so not a problem
  # only test failing for Win is tests/unit/test_mock_s3.py
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip !=21.3
    - pytest-runner
    - setuptools >=40.6.0
    - setuptools_scm >=6.2
  run:
    - python >={{ python_min }}
    - pyfive >=0.5.0
    - dask !=2024.8.0
    - fsspec
    - h5netcdf
    - netcdf4
    - numcodecs >=0.12
    - numpy !=1.24.3
    - requests
    - s3fs >=2024.2.0
    - ujson

test:
  source_files:
    - tests
    - setup.cfg
  requires:
    - python >={{ python_min }}
    - moto
    - pip
    - pytest
    - pytest-cov >=2.10.1
    - pytest-html !=2.1.0
    - pytest-metadata >=1.5.1
    - pytest-xdist
  commands:
    # connection refused (for s3); slow tests; fails for Win
    - pytest -n 2 -m "not slow" --ignore=tests/s3_exploratory/  --ignore=tests/test_real_https.py --ignore=tests/test_real_s3.py --ignore=tests/unit/test_mock_s3.py 
    - python -c "from activestorage import Active"
  imports:
    - activestorage

about:
  home: https://github.com/NCAS-CMS/PyActiveStorage
  license: Apache-2.0
  license_file: LICENSE
  summary: 'PyActiveStorage: provides a Python client to local or remote active storage (aka computational storage).'
  description: 'PyActiveStorage: shrink data transfers by applying data reductions straight in the storage unit.'
  doc_url: https://pyactivestorage.readthedocs.io
  dev_url: https://github.com/NCAS-CMS/PyActiveStorage

extra:
  recipe-maintainers:
    - davidhassell
    - valeriupredoi
